SELECT * WHERE {
	<http://www.wikidata.org/entity/Q3501742> <http://www.wikidata.org/prop/direct/P106> ?x1 .
	?x1 <http://www.wikidata.org/prop/direct/P279>* ?c815 .
	?c815 <http://www.wikidata.org/prop/direct/P425> ?x2 .
}