SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P18> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?x3 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c192 .
	?c192 <http://www.wikidata.org/prop/direct/P279>+ <http://www.wikidata.org/entity/Q2095> .
}