SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P131> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c254 .
	?c254 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q3918> .
}