SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P31> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P625> ?x3 .
	?x1 <http://www.wikidata.org/prop/direct/P131>* <http://www.wikidata.org/entity/Q84> .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c956 .
	?c956 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q3918> .
}