SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P1082> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P17> ?x3 .
	?x1 <http://www.wikidata.org/prop/direct/P625> ?x4 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c806 .
	?c806 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q515> .
}