SELECT * WHERE {
	<http://www.wikidata.org/entity/Q3132941> <http://www.wikidata.org/prop/direct/P106> ?x1 .
	?x1 <http://www.wikidata.org/prop/direct/P279>* ?c601 .
	?c601 <http://www.wikidata.org/prop/direct/P425> ?x2 .
}