SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P686> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c907 .
	?c907 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q2996394> .
}