SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P131> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P137> ?x3 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c414 .
	?c414 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q7075> .
	?x1 <http://www.wikidata.org/prop/direct/P131>* <http://www.wikidata.org/entity/Q25> .
}