SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P17> <http://www.wikidata.org/entity/Q142> .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c335 .
	?c335 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q811979> .
}