SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P1435> <http://www.wikidata.org/entity/Q11691318> .
	?x1 <http://www.wikidata.org/prop/direct/P625> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c948 .
	?c948 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q16970> .
	?x1 <http://www.wikidata.org/prop/direct/P131>* <http://www.wikidata.org/entity/Q1196> .
}