SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P1448> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c198 .
	?c198 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q26243694> .
}