SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P921> <http://www.wikidata.org/entity/Q2763> .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c983 .
	?c983 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q191067> .
}