SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P625> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c15 .
	?c15 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q23442> .
	?x1 <http://www.wikidata.org/prop/direct/P131>+ <http://www.wikidata.org/entity/Q90> .
}