SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P1082> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c85 .
	?c85 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q515> .
}