SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P50> <http://www.wikidata.org/entity/Q14468873> .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c318 .
	?c318 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q571> .
}