SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P31> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P625> ?x3 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c898 .
	?c898 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q486972> .
	?x1 <http://www.wikidata.org/prop/direct/P131>* <http://www.wikidata.org/entity/Q1356> .
}