SELECT * WHERE {
	<http://www.wikidata.org/entity/Q2379472> <http://www.wikidata.org/prop/direct/P106> ?x1 .
	?x1 <http://www.wikidata.org/prop/direct/P279>* ?c325 .
	?c325 <http://www.wikidata.org/prop/direct/P425> ?x2 .
}