SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P19> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c165 .
	?c165 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q82794> .
}