SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P1340> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c132 .
	?c132 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q5> .
}