SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P131> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?x3 .
	?x2 <http://www.wikidata.org/prop/direct/P131>* <http://www.wikidata.org/entity/Q108047> .
	?x3 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q56061> .
}