SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P17> <http://www.wikidata.org/entity/Q836> .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c153 .
	?c153 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q16917> .
}