SELECT * WHERE {
	<http://www.wikidata.org/entity/Q10860948> <http://www.wikidata.org/prop/direct/P106> ?x1 .
	?x1 <http://www.wikidata.org/prop/direct/P279>* ?c237 .
	?c237 <http://www.wikidata.org/prop/direct/P425> ?x2 .
}