SELECT * WHERE {
	?x1 <http://www.wikidata.org/prop/direct/P625> ?x2 .
	?x1 <http://www.wikidata.org/prop/direct/P31> ?c704 .
	?c704 <http://www.wikidata.org/prop/direct/P279>* <http://www.wikidata.org/entity/Q3918> .
	?x1 <http://www.wikidata.org/prop/direct/P131>* <http://www.wikidata.org/entity/Q84> .
}